port: 8081
logsAddress: "./log.log"

#mysql:
#  name: "root"
#  host: "1.117.28.50"
#  port: 1111
#  password: 123456
#  dbName: "test"

postgresql:
  name: "postgres"
  host: "1.117.28.50"
  port: 1111
  password: 123456
  dbName: "GooTask"

redis:
  host: "1.117.28.50"
  port: 9736